# SITE CONFIGURATION
title: "" # your site title
author: 박윤희 # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onlykjh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: 김종한
  links:
    - https://www.linkedin.com/in/BenBalter
    - https://github.com/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - { name: "Home", link: "/" }
  #- { name: "About Me", link: "/about" }
  #- { name: "Contact", link: "/contact" }

tagline: >
hero_img: posts/green.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: scarlet94.park@gmail.com # email for form submission

github_username: onlykjh # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: Han # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  # - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
